[package]
name = "agent"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
#anyhow = "1.0.98"
common = {path="../common"}
ed25519-dalek = "2.1.1"
x25519-dalek = { version = "2.0.1", features = ["serde"] }
