[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.37", features = ["derive"] }
common = {path = "../common"}
ureq = { version = "3.0.11", features = ["json"] }
uuid = { version = "1.16.0", features = ["serde"] }
